### ISSUE TITLE
Neuron M503 group 2 inputs and outputs not available

### ISSUE THREAD

**Issue by noreway** [UniPiTechnology/neuron-tcp-modbus-overlay#2]
**Environment**
- UniPi Neuron M503
- Jessie Lite
- evok (master branch)
- accessing web client with Chrome 59

**Error**
All Modbus registers and coils of group 2 are not accessible. They do not show up in the evok web client.

**Test script**
```python
#!/usr/bin/python
from pymodbus.client.sync import ModbusTcpClient
client = ModbusTcpClient('127.0.0.1')
# read DO 1.1 - 1.4 on unit 0 working
client.read_coils(0, 1, unit=0)
client.read_coils(1, 1, unit=0)
client.read_coils(2, 1, unit=0)
client.read_coils(3, 1, unit=0)

# read DO 1.1 - 1.4 on unit 1 working
client.read_coils(0, 1, unit=1)
client.read_coils(1, 1, unit=1)
client.read_coils(2, 1, unit=1)
client.read_coils(3, 1, unit=1)

# read RO 2.1 - 2.5 on unit 0 NOT working
client.read_coils(100, 1, unit=0)
client.read_coils(101, 1, unit=0)
client.read_coils(102, 1, unit=0)
client.read_coils(103, 1, unit=0)
client.read_coils(104, 1, unit=0)

# read RO 2.1 - 2.5 on unit 2 NOT working
client.read_coils(0, 1, unit=2)
client.read_coils(1, 1, unit=2)
client.read_coils(2, 1, unit=2)
client.read_coils(3, 1, unit=2)
client.read_coils(4, 1, unit=2)
```

**Comment by tomashora** [comment]
This is related to the pymodbus client which is not using the UNIT according to the parameter. Already [discussed in forum](https://forum.unipi.technology/topic/402/modbus-registers-mapping-broken/3).

Closing now, please re-open if I am wrong.

**Comment by noreway** [comment]
@tomashora I've solved the issue. The evok installation (from master branch) is using neuron tcp 1.0.0, after installing neuron tcp 1.0.1 the script above is working fine without changes. In the evok web client the hardware of goup 2 is still missing, but this is maybe an evok issue.
