### ISSUE TITLE
Unable to build overlay with dtc

### ISSUE THREAD

**Issue by eLvErDe** [UniPiTechnology/neuron-tcp-modbus-overlay#4]
Hi,

First issue is the -@ parameter to dtc commands that simply does not exist.
Then I get a syntax error inside the file:
```
dtc -I dts -O dtb -o /home/acecile/packaging/unipi/neuron-tcp-modbus-overlay/neuron-tcp-modbus-overlay-1.0.2/debian/neuron-tcp-modbus-overlay/boot/neuron-spi.dtbo spi_overlay/neuron-spi.dts
Error: spi_overlay/neuron-spi.dts:2.2-8 syntax error
FATAL ERROR: Unable to parse input tree
```

Thanks

**Comment by tknot** [comment]
What version of Raspbian are you using? The command works at least on Jessie and Stretch. 

Note that the x86/AMD64 version of Debian has an entirely different DTC, the overlay is compiled against the specific kernel of the Raspberry PI and has to be compiled there.

**Comment by eLvErDe** [comment]
Hi,
It's a Jessie one. But I just figured out:
I was crossbuilding but Raspbian comes with a custom device-tree-compiler package, RPi specific. After building on real Pi, it does work :)

Btw, may I ask something else ? I'm missing unipi_rtc and unipi_eeprom modules but I can't find them anywhere.
