### ISSUE TITLE
[GENERAL] Documentation on 1-Wire access

### ISSUE THREAD

**Issue by wesleydv** [UniPiTechnology/neuron-tcp-modbus-overlay#5]
The readme states:
> Provides access to 1-Wire as well

However I can't find any documentation about this

**Comment by tknot** [comment]
Edit: This looks to be an error in the documentation

**Comment by wesleydv** [comment]
I know the sensor report their values via the websocket in EVOK however I was wondering on how to access the values over modbus

**Comment by tknot** [comment]
The values are not available over Modbus unfortunately, and will not be for the foreseeable future. Apologies for any confusion, the comment was simply meant to point to EVOK.
